name: Alif-Build-Unix

on:
  push:
    branches: [ "Alif5.0" ]
  pull_request:
    branches: [ "Alif5.0" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: "linuxBuild"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        BUILD-CONFIGURATION: [debug, release]

    steps:
    - uses: actions/checkout@v4
    # - name: configure
    #   run: ./configure
    - name: make
      run: cd linuxBuild && make ${{matrix.BUILD-CONFIGURATION}}
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
